### ISSUE TITLE
Redmine 404 Error

### ISSUE THREAD

**Issue by myaspm** [luisfontes19/redmine_stats#38]
Hello, i'm using Redmine 3.3.0 and trying to get Global Stats plugin to work. For two days the plugin had been giving the 404 error but this morning it magically worked for like 5 minutes and now it's gone again.  Here's my log :

Started GET "/" for 10.100.100.52 at 2016-09-05 14:14:16 +0000
Processing by WelcomeController#index as HTML
Current user: admin (id=1)
Rendered welcome/index.html.erb within layouts/base (5.1ms)
Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (2.9ms)
Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (0.4ms)
Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.4ms)
Completed 200 OK in 54ms (Views: 33.2ms | ActiveRecord: 9.2ms)
Started GET "/global_stats/current_week" for 10.100.100.52 at 2016-09-05 14:14:31 +0000
Processing by StatsController#index as HTML
Parameters: {"time_filter"=>"current_week"}
Current user: admin (id=1)
Completed 404 Not Found in 22ms (ActiveRecord: 6.8ms)

ActiveRecord::RecordNotFound (Couldn't find Project with 'id'=):
app/models/project.rb:310:in `find'
plugins/redmine_stats/app/models/stat.rb:64:in `block in authors'
plugins/redmine_stats/app/models/stat.rb:63:in `each'
plugins/redmine_stats/app/models/stat.rb:63:in `authors'
plugins/redmine_stats/app/controllers/stats_controller.rb:22:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Thanks in advance.

**Comment by martinvonwittich** [comment]
Yup, same problem here.

<pre>
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_custom_css             0.1.6
  redmine_stats                  0.0.3
</pre>

**Comment by umop-aplsdn** [comment]
The problem seems to be with PostgreSQL. Here is how I managed to make it work (warning: I'm not really great with Ruby...):

- on app/models/stat.rb:
> - replaced `Project.find` and `User.find` with `Project.find_by_id` and `User.find_by_id`
> - on `issues_by_priority`, replaced the join with `:joins => 'enumerations'` (somehow `IssuePriority.table_name` is not resolved...)
- on app/views/stats/_sidebar.html.erb, on the line that starts with `<% count=0; @open_issues.each`, replaced `["total"]` with `[3]` and `["closed"]` with `[1]` (the dictionary fails to resolve the column names)
- on app/views/stats/index.html.erb:
> - `@authors` has some error, replaced with `@assignees`
> - every count/total using `@xxxxx.each{....` failed, so I replaced them with `count = aggregate(xxxx, {conditions})`
> - on `chart_author_data`, the variable data1 receives `@authors`, but is never used again... replaced the assignment with `data1 = @assignees` and the remaining `@authors` with `data1`

Attached are the modified files.

**Comment by myaspm** [comment]
Yeah i fixed all (i think) issues with postgresql environment. You can find under my profile, it is named Redmine Stats 2, be my guest, give it a shot.
