### ISSUE TITLE
open the page occured 500 error 

### ISSUE THREAD

**Issue by archonwang** [luisfontes19/redmine_stats#40]
my environment is 

```
rails 4.2.x 
ruby 2.2.x
redmine 3.3.1
```

when I installed it it occured an error. 
the trace-log

> An ActiveRecord::StatementInvalid occurred in stats#index:
>  
>   TypeError: wrong argument type nil (expected String):
>   plugins/redmine_stats/app/models/stat.rb:399:in `count_and_group_by'
>  
>  
> -------------------------------
> Request:
> -------------------------------
>  
> * URL : http://192.168.1.41/global_stats/current_month
>   * HTTP Method: GET
>   * IP address : 192.168.60.238
>   * Parameters : {"controller"=>"stats", "action"=>"index", "time_filter"=>"current_month"}
>   * Timestamp  : 2016-11-14 12:25:47 UTC
>   * Server : jira
>   * Rails root : /opt/redmine-3.3
>   * Process: 437
>  
> -------------------------------
> Session:
> -------------------------------
>  
>   * session id: "dbdacb2e948f3b1c94ee2258cff3ed83"
>   * data: {"session_id"=>"dbdacb2e948f3b1c94ee2258cff3ed83",
>    "user_id"=>8,
>    "tk"=>"0a696dafdd0d62be5ab2996bcc0065f675de337f",
>    "query"=>
>     {:project_id=>2,
>      :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
>      :group_by=>"parent",
>      :column_names=>nil,
>      :totalable_names=>[:estimated_hours]},
>    "issues_index_sort"=>"id:desc",
>    "_csrf_token"=>"LBwnKBkWfyJtvA4xdvYOfQ8xjKrsMqQCktrezjdud9I=",
>    "recent_projects"=>[2],
>    "access_count_table"=>{30=>1, 62=>1, 67=>1},
>    "per_page"=>50}
>  
> -------------------------------
> Environment:
> -------------------------------
>  
>   * GATEWAY_INTERFACE                              : CGI/1.2
>   * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
>   * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
>   * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4
>   * HTTP_CONNECTION                                : keep-alive
>   * HTTP_COOKIE                                    : autologin=47a32fad2a96ff9a5b19bd5e91b8c54a7eadf2ae; _redmine_session=eWZodTdydUpzUFRzckpIQnM5aCtTSk1qU1VNSEtaSWs4MUNZdWRQMGlWWXRLaEp0VzdYS2pxQ2pKVnNjN2UvN3lCakNyc1FmTnFtSFhIakVPUkFZLzZsN2p2N1ZDV01VR2w1bTVhY3djc0p3a1ZSKzJpTGQ5cjMzbDRoUUJ5emRlNWhNMy8xL1MrNHAyRUwwSVpZY2lwMUl1dkcvT3ZUMzlEa0VZbGZLdzJNRG1aOStDb0I5djJIQmticC9DdXBtcWxJZitJazIrWU4yVUM3Rk5wYU04UFppRnZJZnU1dnFudDZhaFAzL0lmVk9WY3htbDgxQWJBbm1oYXg3bXN6Yk55YUwvZ3Ivc2xjY0FMamp4QWUwdmJKdWd2dCs4MElSWWFOUDArU0d3Tk5CMDNmTFo1ZnVkUXpBRE9GQWFTUitxalFFZFFXUmRVcEFBalhhZU9yekdTY2tRVGxLVklSMW9zUk1uckRKdnB2K3Q2b0U0NEZNT2k0QmRTcFozOW8wZXVTd2Q4WnBuTUpyYUJyVjdXU3hGV3VqcFBzYTE3UVdHeXUydVVIemdFR0htMy9MVUdBUFQyakxWRTVCZGxMempQckZtTG1QWTRkM1R4SEZya2NQbTVDTVdnSzZtR1hvRnhyUVNhcjF5WXE3ZEV4RGZqbU1hNEJzWWNQMlhmMm5HZ0E3TTZGVkZXekJyQng4Si9UbGNFZHEyaFZ3Q3l3Snlta1NuQmVXdittSENSSkJwZ0NuRVRkUGJuWDZFdGNYd2ZQRlBmWkpOSTBLOGp4eTNZYjBCcCtMeUNTWVFxbmROSEcxemJiUTRFZ2c4a21lcFZ2K0F3QytzZERZNmJyMDZrZFNsTjhKM1ZBOUdsamFmQ1pjSGc9PS0ta1lkUHNsMkhwUXFHdzB2TEJ1NWFDUT09--a8a100007391d0878d6d66c77e359e02a726a87e
>   * HTTP_HOST                                      : 192.168.1.41
> * HTTP_REFERER : http://192.168.1.41/welcome
>   * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
>   * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
>   * HTTP_VERSION                                   : HTTP/1.1
>   * ORIGINAL_FULLPATH                              : /global_stats/current_month
>   * ORIGINAL_SCRIPT_NAME                           :
>   * PATH_INFO                                      : /global_stats/current_month
>   * QUERY_STRING                                   :
>   * REMOTE_ADDR                                    : 192.168.60.238
>   * REQUEST_METHOD                                 : GET
>   * REQUEST_PATH                                   : /global_stats/current_month
>   * REQUEST_URI                                    : /global_stats/current_month
>   * ROUTES_47407840_SCRIPT_NAME                    :
>   * SCRIPT_NAME                                    :
>   * SERVER_NAME                                    : 192.168.1.41
>   * SERVER_PORT                                    : 80
>   * SERVER_PROTOCOL                                : HTTP/1.1
>   * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
>   * action_controller.instance                     : #<StatsController:0x007f5d8c20cec0>
>   * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000056b7c18>
>   * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f5d8c2fb458>
>   * action_dispatch.cookies_digest                 :
>   * action_dispatch.cookies_serializer             :
>   * action_dispatch.encrypted_cookie_salt          : encrypted cookie
>   * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
>   * action_dispatch.http_auth_salt                 : http authentication
>   * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x000000055a6d60>
>   * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000005b8c8d8>
>   * action_dispatch.parameter_filter               : [:password]
>   * action_dispatch.redirect_filter                : []
>   * action_dispatch.remote_ip                      : 192.168.60.238
>   * action_dispatch.request.content_type           :
>   * action_dispatch.request.formats                : [#<Mime::Type:0x000000038b2330 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=1552748527674330610>]
>   * action_dispatch.request.parameters             : {"controller"=>"stats", "action"=>"index", "time_filter"=>"current_month"}
>   * action_dispatch.request.path_parameters        : {:controller=>"stats", :action=>"index", :time_filter=>"current_month"}
>   * action_dispatch.request.query_parameters       : {}
>   * action_dispatch.request.request_parameters     : {}
>   * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"dbdacb2e948f3b1c94ee2258cff3ed83", "user_id"=>8, "tk"=>"0a696dafdd0d62be5ab2996bcc0065f675de337f", "query"=>{:project_id=>2, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>"parent", :column_names=>nil, :totalable_names=>[:estimated_hours]}, "issues_index_sort"=>"id:desc", "_csrf_token"=>"LBwnKBkWfyJtvA4xdvYOfQ8xjKrsMqQCktrezjdud9I=", "recent_projects"=>[2], "access_count_table"=>{30=>1, 62=>1, 67=>1}, "per_page"=>50}
>   * action_dispatch.request_id                     : 1a90357d-48f8-459a-900c-74690014126b
>   * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000005a6c5c0>
>   * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
>   * action_dispatch.secret_token                   :
>   * action_dispatch.show_detailed_exceptions       : false
>   * action_dispatch.show_exceptions                : true
>   * action_dispatch.signed_cookie_salt             : signed cookie
>   * async.callback                                 : #<Method: Thin::Connection#post_process>
>   * async.close                                    : #<EventMachine::DefaultDeferrable:0x007f5d8c081c68>
>   * rack.errors                                    : #<IO:0x00000001f1d5a0>
>   * rack.input                                     : #<StringIO:0x0000000b33d050>
>   * rack.multiprocess                              : false
>   * rack.multithread                               : true
>   * rack.request.cookie_hash                       : {"autologin"=>"47a32fad2a96ff9a5b19bd5e91b8c54a7eadf2ae", "_redmine_session"=>"eWZodTdydUpzUFRzckpIQnM5aCtTSk1qU1VNSEtaSWs4MUNZdWRQMGlWWXRLaEp0VzdYS2pxQ2pKVnNjN2UvN3lCakNyc1FmTnFtSFhIakVPUkFZLzZsN2p2N1ZDV01VR2w1bTVhY3djc0p3a1ZSKzJpTGQ5cjMzbDRoUUJ5emRlNWhNMy8xL1MrNHAyRUwwSVpZY2lwMUl1dkcvT3ZUMzlEa0VZbGZLdzJNRG1aOStDb0I5djJIQmticC9DdXBtcWxJZitJazIrWU4yVUM3Rk5wYU04UFppRnZJZnU1dnFudDZhaFAzL0lmVk9WY3htbDgxQWJBbm1oYXg3bXN6Yk55YUwvZ3Ivc2xjY0FMamp4QWUwdmJKdWd2dCs4MElSWWFOUDArU0d3Tk5CMDNmTFo1ZnVkUXpBRE9GQWFTUitxalFFZFFXUmRVcEFBalhhZU9yekdTY2tRVGxLVklSMW9zUk1uckRKdnB2K3Q2b0U0NEZNT2k0QmRTcFozOW8wZXVTd2Q4WnBuTUpyYUJyVjdXU3hGV3VqcFBzYTE3UVdHeXUydVVIemdFR0htMy9MVUdBUFQyakxWRTVCZGxMempQckZtTG1QWTRkM1R4SEZya2NQbTVDTVdnSzZtR1hvRnhyUVNhcjF5WXE3ZEV4RGZqbU1hNEJzWWNQMlhmMm5HZ0E3TTZGVkZXekJyQng4Si9UbGNFZHEyaFZ3Q3l3Snlta1NuQmVXdittSENSSkJwZ0NuRVRkUGJuWDZFdGNYd2ZQRlBmWkpOSTBLOGp4eTNZYjBCcCtMeUNTWVFxbmROSEcxemJiUTRFZ2c4a21lcFZ2K0F3QytzZERZNmJyMDZrZFNsTjhKM1ZBOUdsamFmQ1pjSGc9PS0ta1lkUHNsMkhwUXFHdzB2TEJ1NWFDUT09--a8a100007391d0878d6d66c77e359e02a726a87e"}
>   * rack.request.cookie_string                     : autologin=47a32fad2a96ff9a5b19bd5e91b8c54a7eadf2ae; _redmine_session=eWZodTdydUpzUFRzckpIQnM5aCtTSk1qU1VNSEtaSWs4MUNZdWRQMGlWWXRLaEp0VzdYS2pxQ2pKVnNjN2UvN3lCakNyc1FmTnFtSFhIakVPUkFZLzZsN2p2N1ZDV01VR2w1bTVhY3djc0p3a1ZSKzJpTGQ5cjMzbDRoUUJ5emRlNWhNMy8xL1MrNHAyRUwwSVpZY2lwMUl1dkcvT3ZUMzlEa0VZbGZLdzJNRG1aOStDb0I5djJIQmticC9DdXBtcWxJZitJazIrWU4yVUM3Rk5wYU04UFppRnZJZnU1dnFudDZhaFAzL0lmVk9WY3htbDgxQWJBbm1oYXg3bXN6Yk55YUwvZ3Ivc2xjY0FMamp4QWUwdmJKdWd2dCs4MElSWWFOUDArU0d3Tk5CMDNmTFo1ZnVkUXpBRE9GQWFTUitxalFFZFFXUmRVcEFBalhhZU9yekdTY2tRVGxLVklSMW9zUk1uckRKdnB2K3Q2b0U0NEZNT2k0QmRTcFozOW8wZXVTd2Q4WnBuTUpyYUJyVjdXU3hGV3VqcFBzYTE3UVdHeXUydVVIemdFR0htMy9MVUdBUFQyakxWRTVCZGxMempQckZtTG1QWTRkM1R4SEZya2NQbTVDTVdnSzZtR1hvRnhyUVNhcjF5WXE3ZEV4RGZqbU1hNEJzWWNQMlhmMm5HZ0E3TTZGVkZXekJyQng4Si9UbGNFZHEyaFZ3Q3l3Snlta1NuQmVXdittSENSSkJwZ0NuRVRkUGJuWDZFdGNYd2ZQRlBmWkpOSTBLOGp4eTNZYjBCcCtMeUNTWVFxbmROSEcxemJiUTRFZ2c4a21lcFZ2K0F3QytzZERZNmJyMDZrZFNsTjhKM1ZBOUdsamFmQ1pjSGc9PS0ta1lkUHNsMkhwUXFHdzB2TEJ1NWFDUT09--a8a100007391d0878d6d66c77e359e02a726a87e
>   * rack.request.query_hash                        : {}
>   * rack.request.query_string                      :
>   * rack.run_once                                  : false
>   * rack.session                                   : #<ActionDispatch::Request::Session:0x007f5d8c0802a0>
>   * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f5d8c080250>
>   * rack.url_scheme                                : http
>   * rack.version                                   : [1, 0]
>  
> -------------------------------
> Backtrace:
> -------------------------------
>  
>   plugins/redmine_stats/app/models/stat.rb:399:in `count_and_group_by'
>   plugins/redmine_stats/app/models/stat.rb:285:in `issues_by_priority'
>   plugins/redmine_stats/app/controllers/stats_controller.rb:28:in `index'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>

**Comment by archonwang** [comment]
Please help to check it. Thanks.

**Comment by hermanho** [comment]
What database engine and ActiveRecord adaptec are installed in your environment?

**Comment by archonwang** [comment]
@hermanho 
my environment is

```
Environment:
  Redmine version                3.3.1.stable.15949
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```


```
Rails version	4.2.7.1
Ruby version	2.2.4-p230 (x86_64-linux)
RubyGems version	2.4.5.1
Rack version	1.6.4
Middleware	
Rack::Sendfile
ActionDispatch::Static
#<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000005ce6f80>
Rack::Runtime
Rack::MethodOverride
ActionDispatch::RequestId
Rails::Rack::Logger
ActionDispatch::ShowExceptions
ActionDispatch::DebugExceptions
ActionDispatch::RemoteIp
ActionDispatch::Callbacks
ActiveRecord::ConnectionAdapters::ConnectionManagement
ActiveRecord::QueryCache
ActionDispatch::Cookies
ActionDispatch::Session::CookieStore
ActionDispatch::Flash
ActionDispatch::ParamsParser
ActionDispatch::XmlParamsParser
Rack::Head
Rack::ConditionalGet
Rack::ETag
Rack::ContentLength
RequestStore::Middleware
OpenIdAuthentication
ExceptionNotification::Rack
Rack::RawUpload
Application root	/opt/redmine-3.3
Environment	production
Database adapter	mysql2
Database schema version	20160829001530
```

**Comment by hermanho** [comment]
@archonwang , would you please try the branch "sql_server_ifelse" ?
https://github.com/hermanho/redmine_stats/tree/sql_server_ifelse
