### ISSUE TITLE
Values in tables don't link to proper results. 

### ISSUE THREAD

**Issue by skibinstein** [luisfontes19/redmine_stats#7]
I try to display current month statistics for one project. Result looks like 
![assigne](https://cloud.githubusercontent.com/assets/10942661/6186507/3167ea7a-b372-11e4-8a75-6aca0031d928.jpg)

I have 2 opened issues this month. When I click on this value I get list with all opened issues and not only those 2.  

It looks like filters don't include time interval. This problem exists in all tables.

**Comment by skibinstein** [comment]
We are almost there :) 
I try to check open issues assigned to person X in project Y  for last week. Wen I clik on this value I get query only with filters "status" and "created". You miss filters "project" and "assignee to". 

Statistics for Tracker, Priority and Author links to wrong results as well. 

When I try to display statistics since beginning of the time for project X i get following error. It was working before.  

ctionView::Template::Error (undefined method `strftime' for nil:NilClass):
    16: 		<%= aggregate_link data, { field_name => row.id, "closed" => 0 }, 
    17: 				aggregate_path(@project, field_name, row,
    18: 						:op => {"status_id"=>"o", "#{filter_by}"=>"><"}, 
    19: 						"v[#{filter_by}]" => formated_dates(@dates), 
    20: 						"f" => ["status_id", "#{filter_by}", ""]) 
    21: 		%>
    22:   </td>
  plugins/redmine_stats/app/helpers/stats_helper.rb:26:in `format_date'
  plugins/redmine_stats/app/helpers/stats_helper.rb:30:in `formated_dates'
  plugins/redmine_stats/app/views/stats/_simple.html.erb:19:in `block in _plugins_redmine_stats_app_views_stats__simple_html_erb___2124334752665733350_60122780'
  plugins/redmine_stats/app/views/stats/_simple.html.erb:12:in `each'
  plugins/redmine_stats/app/views/stats/_simple.html.erb:12:in `_plugins_redmine_stats_app_views_stats__simple_html_erb___2124334752665733350_60122780'
  actionpack (3.2.19) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.19) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.19) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/partial_renderer.rb:237:in `render'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:15:in `render'
  actionpack (3.2.19) lib/action_view/helpers/rendering_helper.rb:24:in `render'
  plugins/redmine_stats/app/views/stats/index.html.erb:38:in `_plugins_redmine_stats_app_views_stats_index_html_erb___965333205736924432_58698440'
  actionpack (3.2.19) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.19) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.19) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.19) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.19) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.19) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.19) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.19) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.19) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /home/redmine/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (3.2.19) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.19) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.19) lib/active_support/callbacks.rb:491:in `_run__2270217378249676067__process_action__2153878029057182515__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.19) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.19) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.19) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.19) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.19) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.19) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__3661922956704215660__call__2188476615673218424__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.5) lib/rack/lint.rb:48:in `_call'
  rack (1.4.5) lib/rack/lint.rb:36:in `call'
  rack (1.4.5) lib/rack/showexceptions.rb:24:in `call'
  rack (1.4.5) lib/rack/commonlogger.rb:33:in `call'
  rack (1.4.5) lib/rack/chunked.rb:43:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `load'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/unicorn:23:in `<main>'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
  /home/redmine/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by luisfontes19** [comment]
For your second problem, please check if you have the latest version... I've made 2 commits today, and I think I've solved that in the second one

**Comment by skibinstein** [comment]
Yes indeed, you solved second problem.
